version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: config/docker/web.Dockerfile
    container_name: web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn SoftecWeb.wsgi -b 0.0.0.0:80"
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "80"
