# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurant_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(blank=True, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pos'),
        ),
    ]
