# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170619_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
