# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170619_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_file', models.FileField(upload_to=b'', verbose_name=b'File')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantImage',
        ),
    ]
