# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170619_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfile',
            name='resturant_file',
            field=models.FileField(upload_to='%Y/%m/', verbose_name='File'),
        ),
    ]
