# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170619_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant'),
            preserve_default=False,
        ),
    ]
