# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dataitem_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalPasword',
            new_name='GlobalPassword',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='eAutomateID',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'restaurant name'),
        ),
    ]
