# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170620_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='eAutomateID',
            field=models.CharField(help_text=b'All caps - e.g. AZ01', max_length=4, unique=True, verbose_name=b'eAutomate ID'),
        ),
    ]
