# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170613_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='name',
            new_name='pos_name',
        ),
    ]
