# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170613_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pos',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
