# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170613_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(to='core.Customer'),
        ),
    ]
